#!/usr/bin/env bash
# Link config files

main(){
    mkdir -p "$HOME/.config/lvim/"
    mkdir -p "$HOME/.config/nvim/"
    mkfir -p "$HOME/.config/fish/"
    cp lvim/config.lua "$HOME/.config/lvim/"
    cp nvim/init.vim "$HOME/.config/nvim/"
    cp fish/config.fish "$HOME/.config/fish/"
    cp .gitignore "$HOME/"
    cp .gitconfig "$HOME/"
}

main "$@"
