#!/usr/bin/env bash
# Link config files
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 || exit 1 ; pwd -P )"
echo $SCRIPTPATH
main(){
    for i in "$@"
    do
        if [ "$i" == "git" ]; then
            cp $SCRIPTPATH/.git* "$HOME/"
        fi
        mkdir -p "$HOME/.config/$i"
        cp $SCRIPTPATH/"$i"/* "$HOME/.config/$i/"
    done
}

main "$@"
